services:
  - type: web
    runtime: python
    name: pytele-loader
    repo: https://github.com/h0-qp/CountdownTimer-TeLeTiPs
    branch: main
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 teletips_set.py
    autoDeploy: false
    envVars:
      - key: REPO_URL
        sync: false
      - key: REPO_BRANCH
        sync: false
      - key: START_CMD
        sync: false
      - key: PORT
        value: 80
